### ISSUE TITLE
Avoiding lot's of genservers

### ISSUE THREAD

**Issue by houshuang** [adamkittelson/dogstatsd-elixir#3]
I'm just trying to integrate this into Phoenix, where I need to call it in a few different places (a plug, Ecto repo logger etc). Initially I would always get {:ok, dogstatsd} and then do something with dogstats like it says in the documentation. However, then I realized that I'm starting a new gen_server each time, which seems very unnecessary. However, when I tried to put the call to new in my Plug.init, and then get it through call(conn, opts), Phoenix crashed over a gen_server timeout with :get_tags. I'm not sure what determines the lifetime of the gen_server?

I've been reading up on OTP, but I haven't done much of it myself, mostly using Phoenix, Ecto etc. However, wouldn't it make more sense to make it a named link, sitting behind a supervisor which restarts the gen_server whenever it dies? I do not need two different dogstatsd connections in my server, and don't want to build a lot of machinery on my side to maintain a persistent reference to the single gen_server... 

Or what is the best strategy for managing this in a large app where you call dogstatsd from multiple locations?

thanks!

**Comment by crertel-packlane** [comment]
@adamkittelson was there ever an answer for this?

**Comment by adamkittelson** [comment]
Sorry, somehow missed the initial issue and didn't see this until your comment just now @crertel-packlane 

Since it's just a GenServer you can add a worker for it to your supervision tree like any other GenServer, something like:

`worker(DogStatsd, [datadog_config, [name: :datadog]])` where datadog_config is your configuration, then wherever you want to use it you'd use the name (`:datadog` in this case) rather than the pid.

As far as why starting it in Plug.init wouldn't work, I'm pretty sure things in Plug.init happen at compile time, so any GenServer started there would die as soon as your code finished compiling.

**Comment by crertel-packlane** [comment]
Ah, thanks!

You might want to add that to the docs so people don't think they need to init it per-module or anything. :)

**Comment by crertel-packlane** [comment]
Also, would you accept a PR to add BEAM monitoring similar to what [dogstatsde](https://github.com/WhoopInc/dogstatsde) does someday?

**Comment by crertel-packlane** [comment]
(poking @adamkittelson )
